name: Deploy

on:
  push:
    branches:
      - main  # Ветка, по пушу в которую будет запускаться деплой

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build
    
    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to frontend server
      run: scp -r . root@89.111.134.237:/var/www/daisa.ru/abkhazia-admin/
       
    - name: Deploy frontend
      run: |
        ssh root@89.111.134.237 << 'EOF'
        cd /var/www/daisa.ru/abkhazia-frontend/
        npm install
        pm2 restart daisa-frontend
        EOF
